---
version: "2"

services:
  demo-app:
    build: .
    environment:
      - MODE=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/code
    depends_on:
      - redis
    ports:
      - "9091:9090"
    links:
      - "redis"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data:/usr/share/elasticsearch/data